//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AmountAdd
    {
        public int AccountId { get; set; }
        [Required(ErrorMessage ="Account Number should be provided")]
        public string AccountNo { get; set; }
        //[Required(ErrorMessage = "Account Number should be provided")]
        //public string AccountNo1 { get; set; }
       
        public Nullable<double> Amount { get; set; }
    }
}
